#!/bin/bash

git config --global alias.ad "add" 
git config --global alias.adu "add -u"
git config --global alias.bl "blame"
git config --global alias.br "branch"
git config --global alias.cl "clean"
git config --global alias.cln "clone"
git config --global alias.cm "commit"
git config --global alias.ck "checkout"
git config --global alias.df "diff"
git config --global alias.dfc "diff --cached"
git config --global alias.ds "describe"
git config --global alias.ft "fetch"
git config --global alias.gp "grep"
git config --global alias.in "init"
git config --global alias.lg "log"
git config --global alias.lgh "log HEAD"
git config --global alias.mg "merge"
git config --global alias.pl "pull"
git config --global alias.plh "pull origin HEAD"
git config --global alias.ps "push"
git config --global alias.psh "push origin HEAD"
git config --global alias.rb "rebase"
git config --global alias.rs "restore"
git config --global alias.rss "restore --staged"
git config --global alias.rst "reset"
git config --global alias.rt "remote"
git config --global alias.rv "revert"
git config --global alias.sb "branch --show-current"
git config --global alias.sh "show"
git config --global alias.st "status"
git config --global alias.sth "stash"
git config --global alias.sw "switch"
git config --global alias.tg "tag"
