#!/bin/bash

git config --global alias.ad "add"
git config --global alias.ada "add ."
git config --global alias.adu "add --update"
git config --global alias.bl "blame"
git config --global alias.br "branch"
git config --global alias.brd "branch --delete"
git config --global alias.brl "branch --list"
git config --global alias.cfg "config"
git config --global alias.cfgl "config --list"
git config --global alias.cln "clean"
git config --global alias.clf "clean --force"
git config --global alias.clo "clone"
git config --global alias.cha "cherry-pick --abort"
git config --global alias.chc "cherry-pick --continue"
git config --global alias.chp "cherry-pick"
git config --global alias.cm "commit"
git config --global alias.cmf "commit --fixup"
git config --global alias.cma "commit --amend"
git config --global alias.cmn "commit --amend --no-edit"
git config --global alias.cmm "commit --message"
git config --global alias.ck "checkout"
git config --global alias.df "diff"
git config --global alias.dfc "diff --cached"
git config --global alias.ds "describe"
git config --global alias.ft "fetch"
git config --global alias.ftp "fetch --prune"
git config --global alias.gp "grep"
git config --global alias.in "init"
git config --global alias.lg "log"
git config --global alias.lgo "log --graph --oneline --decorate --all"
git config --global alias.lgh "log HEAD"
git config --global alias.lgp "log --patch"
git config --global alias.mg "merge"
git config --global alias.mga "merge --abort"
git config --global alias.mgc "merge --continue"
git config --global alias.mgs "merge --squash"
git config --global alias.pl "pull"
git config --global alias.plh "pull origin HEAD"
git config --global alias.ps "push"
git config --global alias.psf "push --force-with-lease"
git config --global alias.psh "push origin HEAD"
git config --global alias.pshf "push origin HEAD --force-with-lease"
git config --global alias.rb "rebase"
git config --global alias.rba "rebase --abort"
git config --global alias.rbc "rebase --continue"
git config --global alias.rbi "rebase --interactive"
git config --global alias.rs "restore"
git config --global alias.rsa "restore ."
git config --global alias.rss "restore --staged"
git config --global alias.rst "reset"
git config --global alias.rt "remote"
git config --global alias.rv "revert"
git config --global alias.scb "branch --show-current"
git config --global alias.sh "show"
git config --global alias.st "status"
git config --global alias.sts "status --short --branch"
git config --global alias.sth "stash"
git config --global alias.sthd "stash drop"
git config --global alias.sthl "stash list"
git config --global alias.stho "stash pop"
git config --global alias.sthp "stash push"
git config --global alias.stha "stash apply"
git config --global alias.sths "stash show --patch"
git config --global alias.sw "switch"
git config --global alias.swc "switch --create"
git config --global alias.tg "tag"
